name: word-complex-project

services:
  frontend:
    build: ./client
    container_name: vite-app
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

    restart: unless-stopped

    networks:
      - word-complex
  express:
    build: ./server
    container_name: express-server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped
    networks:
      - word-complex

networks:
  word-complex:
    driver: bridge
