name: word-complex-project

services:
  next-app:
    build: ./client
    container_name: nextjs-app
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

    restart: unless-stopped

    networks:
      - word-complex
  express:
    build: ./server
    container_name: express-server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped
    networks:
      - word-complex

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - word-complex

volumes:
  mongo_data:

networks:
  word-complex:
    driver: bridge
