services:
  express:
    build: .
    container_name: express-server

    ports:
      - "3000:3000"

    volumes:
      - .:/app
      - /app/node_modules

    environment:
      - NODE_ENV=development

    command: npm run dev

    restart: unless-stopped

    networks:
      - word-complex

networks:
  word-complex:
